using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Text.Json;
using Quantum.IO.DebugViewport.V1;

namespace Quantum.Debug
{
    public static class DebugViewportSnapshotPreviewIndex
    {
        public const string FileName = "snapshot-preview-index.md";
        public const string GalleryFileName = "index.html";

        private const string ArtifactsDirectoryName = "artifacts";
        private const string DebugViewportDirectoryName = "debug-viewport";

        private static readonly UTF8Encoding Utf8NoBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

        public static bool TryWriteForGeneratedOutput(string generatedOutputPath, TextWriter? output = null)
        {
            if (string.IsNullOrWhiteSpace(generatedOutputPath))
            {
                return false;
            }

            string resolvedGeneratedOutputPath = Path.GetFullPath(generatedOutputPath);
            if (!TryResolveDebugViewportArtifactDirectory(
                    resolvedGeneratedOutputPath,
                    out string artifactDirectory,
                    out string relativeBaseDirectory))
            {
                return false;
            }

            string indexPath = Path.Combine(artifactDirectory, FileName);
            WriteIndex(artifactDirectory, indexPath, relativeBaseDirectory);
            output?.WriteLine($"Updated snapshot preview index at '{indexPath}'.");
            return true;
        }

        public static void WriteIndex(
            string artifactDirectory,
            string? outputMarkdownPath = null,
            string? relativeBaseDirectory = null)
        {
            if (string.IsNullOrWhiteSpace(artifactDirectory))
            {
                throw new ArgumentException("Artifact directory is required.", nameof(artifactDirectory));
            }

            string resolvedArtifactDirectory = Path.GetFullPath(artifactDirectory);
            string resolvedOutputMarkdownPath = string.IsNullOrWhiteSpace(outputMarkdownPath)
                ? Path.Combine(resolvedArtifactDirectory, FileName)
                : Path.GetFullPath(outputMarkdownPath);
            string resolvedRelativeBaseDirectory = string.IsNullOrWhiteSpace(relativeBaseDirectory)
                ? ResolveDefaultRelativeBaseDirectory(resolvedArtifactDirectory)
                : Path.GetFullPath(relativeBaseDirectory);

            Directory.CreateDirectory(resolvedArtifactDirectory);

            IReadOnlyList<SnapshotPreviewIndexEntry> entries = CollectEntries(resolvedArtifactDirectory);
            string markdown = BuildMarkdown(
                resolvedArtifactDirectory,
                resolvedOutputMarkdownPath,
                resolvedRelativeBaseDirectory,
                entries,
                DateTimeOffset.UtcNow);

            string? parentDirectory = Path.GetDirectoryName(resolvedOutputMarkdownPath);
            if (!string.IsNullOrEmpty(parentDirectory))
            {
                Directory.CreateDirectory(parentDirectory);
            }

            File.WriteAllText(resolvedOutputMarkdownPath, markdown, Utf8NoBom);
        }

        private static string BuildMarkdown(
            string artifactDirectory,
            string outputMarkdownPath,
            string relativeBaseDirectory,
            IReadOnlyList<SnapshotPreviewIndexEntry> entries,
            DateTimeOffset generatedAtUtc)
        {
            var builder = new StringBuilder();
            string displayDirectory = ToDisplayPath(Path.GetRelativePath(relativeBaseDirectory, artifactDirectory));

            builder.AppendLine("# Technical Preview 0.1 Debug Artifact Index");
            builder.AppendLine();
            builder.AppendLine("Generated: `" + FormatTimestamp(generatedAtUtc) + "`");
            builder.AppendLine("Directory: `" + displayDirectory + "`");
            builder.AppendLine();
            builder.AppendLine("This README-style index is generated by Quantum.Debug when debug viewport outputs are written under `artifacts/debug-viewport`.");
            builder.AppendLine("The files listed here are backend/debug-preview artifacts only; they are not a real frontend, renderer, editor, or a TrainPoseExportV1 schema change.");
            builder.AppendLine();
            AppendOpenFirstSection(builder, artifactDirectory, outputMarkdownPath, relativeBaseDirectory);
            builder.AppendLine();
            AppendArtifactTypeGuide(builder);
            builder.AppendLine();

            if (entries.Count == 0)
            {
                builder.AppendLine("_No debug viewport snapshot or SVG preview files were found._");
                return builder.ToString();
            }

            string linkBaseDirectory = Path.GetDirectoryName(outputMarkdownPath) ?? artifactDirectory;

            builder.AppendLine("## Generated Snapshot Pairs");
            builder.AppendLine();
            builder.AppendLine("| # | Last Written (UTC) | Represents | TrainPose | Cars | Snapshot JSON | SVG Preview |");
            builder.AppendLine("|---:|---|---|---|---:|---|---|");

            for (int i = 0; i < entries.Count; i++)
            {
                SnapshotPreviewIndexEntry entry = entries[i];
                builder.Append("| ");
                builder.Append((i + 1).ToString(CultureInfo.InvariantCulture));
                builder.Append(" | `");
                builder.Append(FormatTimestamp(entry.LastWrittenUtc));
                builder.Append("` | ");
                builder.Append(EscapeMarkdownTableText(entry.Description));
                builder.Append(" | ");
                builder.Append(EscapeMarkdownTableText(entry.Metadata.TrainPosePresence));
                builder.Append(" | ");
                builder.Append(EscapeMarkdownTableText(entry.Metadata.TrainPoseCarCount));
                builder.Append(" | ");
                builder.Append(FormatFileLink(entry.SnapshotFile, relativeBaseDirectory, linkBaseDirectory));
                builder.Append(" | ");
                builder.Append(FormatFileLink(entry.PreviewFile, relativeBaseDirectory, linkBaseDirectory));
                builder.AppendLine(" |");
            }

            return builder.ToString();
        }

        private static void AppendOpenFirstSection(
            StringBuilder builder,
            string artifactDirectory,
            string outputMarkdownPath,
            string relativeBaseDirectory)
        {
            string linkBaseDirectory = Path.GetDirectoryName(outputMarkdownPath) ?? artifactDirectory;
            string galleryPath = Path.Combine(artifactDirectory, GalleryFileName);
            string browserPath = Path.Combine(artifactDirectory, DebugViewportSnapshotBrowserCommand.DefaultFileName);
            string displayGalleryPath = ToDisplayPath(Path.GetRelativePath(relativeBaseDirectory, galleryPath));
            string galleryLinkPath = ToDisplayPath(Path.GetRelativePath(linkBaseDirectory, galleryPath));
            string displayBrowserPath = ToDisplayPath(Path.GetRelativePath(relativeBaseDirectory, browserPath));
            string browserLinkPath = ToDisplayPath(Path.GetRelativePath(linkBaseDirectory, browserPath));

            builder.AppendLine("## Open First");
            builder.AppendLine();
            builder.AppendLine("- Static gallery: [`" + EscapeMarkdownCode(displayGalleryPath) + "`](" + EscapeMarkdownLink(galleryLinkPath) + ") - local HTML generated by the demo script for scanning all SVG previews.");
            builder.AppendLine("- Browser inspector: [`" + EscapeMarkdownCode(displayBrowserPath) + "`](" + EscapeMarkdownLink(browserLinkPath) + ") - local HTML/SVG/vanilla JavaScript viewer for snapshot JSON layers, distance labels, and sample measurement readouts.");
            builder.AppendLine("- This index: generated map of JSON snapshots, paired SVG previews, and what each artifact is meant to prove.");
            builder.AppendLine("- JSON snapshots: renderer-neutral `DebugViewportSnapshotV1` data for contract validation and optional thin adapters.");
            builder.AppendLine("- SVG previews: backend-only technical previews for centerline, elevation, raw sample, frame, debug-line, and oriented train-box sanity checks.");
        }

        private static void AppendArtifactTypeGuide(StringBuilder builder)
        {
            builder.AppendLine("## Artifact Types");
            builder.AppendLine();
            builder.AppendLine("| Type | Represents | Use For |");
            builder.AppendLine("|---|---|---|");
            builder.AppendLine("| JSON snapshot | `DebugViewportSnapshotV1` renderer-neutral backend data: sampled centerline points, stable frames, optional debug lines, optional train boxes, and optional embedded `TrainPoseExportV1`. | Contract validation, importer checks, and debug adapter handoff. |");
            builder.AppendLine("| SVG preview | Multi-panel technical debug preview rendered from one JSON snapshot. It shows top-down X/Z, elevation/profile, raw exported points, raw centerline, frame ticks, debug lines, oriented train boxes, and preview-only smoothing. | Fast visual sanity checks without Unity, Unreal, or a frontend. |");
            builder.AppendLine("| HTML gallery | Static local gallery written by `tools/demo-technical-preview-0.1.ps1` that embeds the generated SVG previews and links to their source JSON. | First-pass Technical Preview review of the generated sample set. |");
            builder.AppendLine("| Browser inspector | Static local HTML/SVG/vanilla JavaScript viewer written by `debug-viewport-snapshot-v1-browser`. It embeds snapshot JSON and adds layer toggles for centerline samples, distance labels/ticks, frame axes, debug lines, train boxes, bogie markers, wheel markers, metadata, and sample measurement readouts. | Artifact-first inspection of backend correctness without adding frontend packages or changing contracts. |");
        }

        private static string CreateDescription(string stem)
        {
            if (string.Equals(stem, "DebugViewportSnapshotV1.sample", StringComparison.OrdinalIgnoreCase))
            {
                return "Built-in backend sample with sampled centerline, frames, debug axes, simple train boxes, and embedded TrainPoseExportV1.";
            }

            if (string.Equals(stem, "DebugViewportSnapshotV1.banking-profile.sample", StringComparison.OrdinalIgnoreCase))
            {
                return "BankingProfile train-pose sample with oriented train boxes and nested TrainPoseExportV1 from the opt-in BankingProfile pose path.";
            }

            if (stem.StartsWith("Milestone7.synthetic.", StringComparison.OrdinalIgnoreCase))
            {
                string fixtureName = stem.Substring("Milestone7.synthetic.".Length).Replace('_', ' ');
                return "Milestone 7 synthetic " + fixtureName + " CSV fixture converted to DebugViewportSnapshotV1 for centerline/frame preview.";
            }

            return "DebugViewportSnapshotV1 snapshot output and its paired backend-only SVG preview.";
        }

        private static IReadOnlyList<SnapshotPreviewIndexEntry> CollectEntries(string artifactDirectory)
        {
            var entries = new List<SnapshotPreviewIndexEntry>();
            var previewFilesByBasePath = new Dictionary<string, FileInfo>(StringComparer.OrdinalIgnoreCase);
            var usedPreviewPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (string previewPath in Directory.EnumerateFiles(artifactDirectory, "*.svg", SearchOption.AllDirectories))
            {
                var previewFile = new FileInfo(previewPath);
                previewFilesByBasePath[Path.ChangeExtension(previewFile.FullName, null) ?? previewFile.FullName] = previewFile;
            }

            foreach (string snapshotPath in Directory.EnumerateFiles(artifactDirectory, "*.json", SearchOption.AllDirectories))
            {
                var snapshotFile = new FileInfo(snapshotPath);
                string basePath = Path.ChangeExtension(snapshotFile.FullName, null) ?? snapshotFile.FullName;
                previewFilesByBasePath.TryGetValue(basePath, out FileInfo? previewFile);

                if (previewFile != null)
                {
                    usedPreviewPaths.Add(previewFile.FullName);
                }

                entries.Add(new SnapshotPreviewIndexEntry(snapshotFile, previewFile));
            }

            foreach (FileInfo previewFile in previewFilesByBasePath.Values)
            {
                if (!usedPreviewPaths.Contains(previewFile.FullName))
                {
                    entries.Add(new SnapshotPreviewIndexEntry(snapshotFile: null, previewFile));
                }
            }

            entries.Sort(CompareEntries);
            return entries;
        }

        private static int CompareEntries(SnapshotPreviewIndexEntry left, SnapshotPreviewIndexEntry right)
        {
            int sortComparison = string.Compare(left.SortKey, right.SortKey, StringComparison.OrdinalIgnoreCase);
            if (sortComparison != 0)
            {
                return sortComparison;
            }

            int timestampComparison = left.LastWrittenUtc.CompareTo(right.LastWrittenUtc);
            return timestampComparison != 0
                ? timestampComparison
                : string.Compare(left.SortPath, right.SortPath, StringComparison.OrdinalIgnoreCase);
        }

        private static string GetStem(FileInfo? snapshotFile, FileInfo? previewFile)
        {
            string fileName = snapshotFile?.Name ?? previewFile?.Name ?? string.Empty;
            string stem = Path.GetFileNameWithoutExtension(fileName);
            if (stem.EndsWith(".snapshot", StringComparison.OrdinalIgnoreCase))
            {
                stem = stem.Substring(0, stem.Length - ".snapshot".Length);
            }

            return stem;
        }

        private static string CreateSortKey(string stem, string sortPath)
        {
            if (string.Equals(stem, "DebugViewportSnapshotV1.sample", StringComparison.OrdinalIgnoreCase))
            {
                return "0:0:" + sortPath;
            }

            if (string.Equals(stem, "DebugViewportSnapshotV1.banking-profile.sample", StringComparison.OrdinalIgnoreCase))
            {
                return "0:1:" + sortPath;
            }

            if (stem.StartsWith("Milestone7.synthetic.", StringComparison.OrdinalIgnoreCase))
            {
                return "1:" + sortPath;
            }

            return "2:" + sortPath;
        }

        private static string FormatFileLink(FileInfo? file, string displayBaseDirectory, string linkBaseDirectory)
        {
            if (file == null)
            {
                return "_not generated_";
            }

            string displayPath = ToDisplayPath(Path.GetRelativePath(displayBaseDirectory, file.FullName));
            string linkPath = ToDisplayPath(Path.GetRelativePath(linkBaseDirectory, file.FullName));
            return "[`" + EscapeMarkdownCode(displayPath) + "`](" + EscapeMarkdownLink(linkPath) + ")";
        }

        private static string ResolveDefaultRelativeBaseDirectory(string artifactDirectory)
        {
            var directory = new DirectoryInfo(artifactDirectory);
            if (IsDebugViewportArtifactDirectory(directory) &&
                directory.Parent?.Parent != null)
            {
                return directory.Parent.Parent.FullName;
            }

            return directory.FullName;
        }

        private static bool TryResolveDebugViewportArtifactDirectory(
            string resolvedGeneratedOutputPath,
            out string artifactDirectory,
            out string relativeBaseDirectory)
        {
            string? outputDirectory = Path.GetDirectoryName(resolvedGeneratedOutputPath);
            if (string.IsNullOrWhiteSpace(outputDirectory))
            {
                artifactDirectory = string.Empty;
                relativeBaseDirectory = string.Empty;
                return false;
            }

            var directory = new DirectoryInfo(outputDirectory);
            while (directory != null)
            {
                if (IsDebugViewportArtifactDirectory(directory))
                {
                    artifactDirectory = directory.FullName;
                    relativeBaseDirectory = directory.Parent?.Parent?.FullName ?? directory.FullName;
                    return true;
                }

                directory = directory.Parent;
            }

            artifactDirectory = string.Empty;
            relativeBaseDirectory = string.Empty;
            return false;
        }

        private static bool IsDebugViewportArtifactDirectory(DirectoryInfo directory)
        {
            return string.Equals(directory.Name, DebugViewportDirectoryName, StringComparison.OrdinalIgnoreCase) &&
                   directory.Parent != null &&
                   string.Equals(directory.Parent.Name, ArtifactsDirectoryName, StringComparison.OrdinalIgnoreCase);
        }

        private static string ToDisplayPath(string path)
        {
            return path.Replace(Path.DirectorySeparatorChar, '/').Replace(Path.AltDirectorySeparatorChar, '/');
        }

        private static string EscapeMarkdownCode(string value)
        {
            return value.Replace("`", "\\`").Replace("|", "\\|");
        }

        private static string EscapeMarkdownTableText(string value)
        {
            return value.Replace("|", "\\|");
        }

        private static string EscapeMarkdownLink(string value)
        {
            return value.Replace(" ", "%20").Replace(")", "%29");
        }

        private static string FormatTimestamp(DateTimeOffset value)
        {
            return value.UtcDateTime.ToString("O", CultureInfo.InvariantCulture);
        }

        private sealed class SnapshotPreviewIndexEntry
        {
            public SnapshotPreviewIndexEntry(FileInfo? snapshotFile, FileInfo? previewFile)
            {
                SnapshotFile = snapshotFile;
                PreviewFile = previewFile;

                DateTimeOffset lastWrittenUtc = snapshotFile == null
                    ? GetLastWriteTimeUtc(previewFile!)
                    : GetLastWriteTimeUtc(snapshotFile);

                if (previewFile != null)
                {
                    DateTimeOffset previewLastWrittenUtc = GetLastWriteTimeUtc(previewFile);
                    if (previewLastWrittenUtc > lastWrittenUtc)
                    {
                        lastWrittenUtc = previewLastWrittenUtc;
                    }
                }

                LastWrittenUtc = lastWrittenUtc;
                SortPath = snapshotFile?.FullName ?? previewFile?.FullName ?? string.Empty;
                string stem = GetStem(snapshotFile, previewFile);
                Description = CreateDescription(stem);
                SortKey = CreateSortKey(stem, SortPath);
                Metadata = SnapshotPreviewIndexMetadata.Read(snapshotFile);
            }

            public FileInfo? SnapshotFile { get; }

            public FileInfo? PreviewFile { get; }

            public DateTimeOffset LastWrittenUtc { get; }

            public string SortPath { get; }

            public string SortKey { get; }

            public string Description { get; }

            public SnapshotPreviewIndexMetadata Metadata { get; }

            private static DateTimeOffset GetLastWriteTimeUtc(FileInfo file)
            {
                return new DateTimeOffset(file.LastWriteTimeUtc, TimeSpan.Zero);
            }
        }

        private sealed class SnapshotPreviewIndexMetadata
        {
            private SnapshotPreviewIndexMetadata(string trainPosePresence, string trainPoseCarCount)
            {
                TrainPosePresence = trainPosePresence;
                TrainPoseCarCount = trainPoseCarCount;
            }

            public string TrainPosePresence { get; }

            public string TrainPoseCarCount { get; }

            public static SnapshotPreviewIndexMetadata Read(FileInfo? snapshotFile)
            {
                if (snapshotFile == null)
                {
                    return new SnapshotPreviewIndexMetadata("<unavailable>", "<unavailable>");
                }

                try
                {
                    string json = File.ReadAllText(snapshotFile.FullName);
                    DebugViewportSnapshotV1Dto dto = DebugViewportSnapshotV1Json.Deserialize(json);
                    return new SnapshotPreviewIndexMetadata(
                        dto.TrainPose == null ? "no" : "yes",
                        Count(dto.TrainPose?.Cars).ToString(CultureInfo.InvariantCulture));
                }
                catch (Exception ex) when (IsReadOrParseException(ex))
                {
                    return new SnapshotPreviewIndexMetadata("<unavailable>", "<unavailable>");
                }
            }

            private static int Count<T>(T[]? values)
            {
                return values == null ? 0 : values.Length;
            }

            private static bool IsReadOrParseException(Exception ex)
            {
                return ex is IOException ||
                       ex is UnauthorizedAccessException ||
                       ex is ArgumentException ||
                       ex is NotSupportedException ||
                       ex is JsonException ||
                       ex is InvalidOperationException;
            }
        }
    }
}
